name: Python Template CI

on:
  push:
    branches: [main]
    paths:
      - "templates/python-uv/**"
      - ".github/workflows/python-ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "templates/python-uv/**"
      - ".github/workflows/python-ci.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./templates/python-uv
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "./templates/python-uv/pyproject.toml"

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
        shell: bash

      - name: Add uv to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        shell: bash

      - name: Install dependencies
        run: |
          uv sync --dev
          uv pip install flake8 black isort mypy pip-audit
        shell: bash

      - name: Run linting checks
        run: |
          uv run black --check .
          uv run flake8 .
          uv run isort --check-only .
          uv run mypy src tests
        shell: bash

      - name: Scan for vulnerabilities
        run: uv run pip-audit
        shell: bash

      - name: Run tests
        run: uv run pytest --cov=src --cov-report=term-missing --cov-report=xml:coverage.xml --cov-fail-under=80
        shell: bash

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./templates/python-uv/coverage.xml
          if-no-files-found: error
